### ISSUE TITLE
Need a client access to webservice?

### ISSUE THREAD

**Issue by ashwin-raj** [phstc/JavaQuickBooksWebConnector#1]
I run this project and try to connect the web services from web services client. But it is not connecting to quick book web connector? Do you know why?

**Comment by phstc** [comment]
Hey @ashwin-raj 

Are the QuickBooks Web Connector urls correct? This project is from 2010 and I'm not developing with QuickBooks anymore, maybe they've changed something.

Did you follow the steps in the README?

**Comment by ashwin-raj** [comment]
Yes the urls are correct. I am creating new client application for the web service and try to access the server.
If I am calling from web connector it is working fine. But I am using a client application the server could not make a connection between server and web connector.

**Comment by phstc** [comment]
Are both urls available to each other? Can you ping your server from the Web Connector vice and versa?

> Pay attention in AppURL, HTTP is only permitted for localhost, for the “internet” you must use HTTPS.

If the AppURL isn't localhost it must be HTTPS. You can use a self-signed certificate, but remember to install it in the server.

Please, let me know if it helped.

**Comment by ashwin-raj** [comment]
Currently I am using localhost only. Are both urls available to each other? I don't understand the question. I connect the server from web connector its working fine. If i am connecting from the client application then only the problem occure

**Comment by phstc** [comment]
> Are both urls available to each other?

When you register an application in the QuickBooks Web Connector, the QBWC will access your Web Service, access QuickBooks then access your Web Service again.

QBWC flow (when I used it ~ 2010, I don't know if it has change since then):
1. (request 1) QBWC asks to your Web Service "what do you want?"
2. (response 1) Your Web Service replies "give me a list of orders"
3. (internal call) QBWC asks to QuickBooks a list of orders
4. (internal call) QuickBooks replies a list of orders to QBWC
5. (request 2) QBWC sends the list of orders to your Web Service
6. (response 2) Your Web Service replies "give me more orders" or "thanks, I don't need more orders"

In which step is your communication failing? Can you `ping [your web service host]` from where the QuickBooks Web Connector is installed?

**Comment by ashwin-raj** [comment]
Ok i understood. The QBWC only make a call to web server. We cannot invokes from our own clients
